# Generated by Django 5.0.3 on 2024-03-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_maincontent_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='maincontent',
            name='header',
        ),
        migrations.RemoveField(
            model_name='maincontent',
            name='sub_header',
        ),
    ]
