# Generated by Django 5.0.3 on 2024-03-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_feature_icon_remove_maincontent_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontent',
            name='title_text',
            field=models.CharField(default='Default title', max_length=255),
            preserve_default=False,
        ),
    ]
